use crate::color::heat;
use crate::fmt::{dec1, group, whole};
use crate::stats::{Report, Stats};

const STYLES: &str = r#"
body { font-family: system-ui, -apple-system, sans-serif; margin: 2rem auto; max-width: 760px; color: #1a1a1a; background: #fff; line-height: 1.4; }
h1 { font-size: 1.3rem; }
h2 { font-size: 1rem; margin-top: 2rem; }
.stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr)); gap: .6rem; margin: 1.2rem 0; }
.stat { background: #f6f6f6; border-radius: 8px; padding: .6rem .8rem; }
.stat b { display: block; font-size: 1.2rem; }
.stat span { font-size: .75rem; color: #666; }
table { border-collapse: collapse; width: 100%; }
th, td { padding: .4rem .7rem; border-bottom: 1px solid #eee; text-align: right; }
th:first-child, td:first-child { text-align: left; }
svg { width: 100%; height: auto; margin: 1rem 0; }
.foot { margin-top: 2rem; color: #999; font-size: .75rem; }
"#;

pub fn export(report: &Report, path: &str) -> anyhow::Result<()> {
    let stats = report.stats();
    let page = format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>auger — {url}</title>
<style>{styles}</style>
</head>
<body>
<h1>auger — {url}</h1>
<div class="stats">
  <div class="stat"><b>{rps}</b><span>req/s</span></div>
  <div class="stat"><b>{requests}</b><span>requests</span></div>
  <div class="stat"><b>{errors}</b><span>errors</span></div>
  <div class="stat"><b>{mean} ms</b><span>mean</span></div>
  <div class="stat"><b>{p99} ms</b><span>p99</span></div>
  <div class="stat"><b>{secs} s</b><span>duration</span></div>
</div>
{chart}
<h2>percentiles (ms)</h2>
<table>
  <tr><th>mean</th><th>p50</th><th>p75</th><th>p90</th><th>p95</th><th>p99</th><th>max</th></tr>
  <tr><td>{mean}</td><td>{p50}</td><td>{p75}</td><td>{p90}</td><td>{p95}</td><td>{p99}</td><td>{max}</td></tr>
</table>
<p class="foot">generated by auger</p>
</body>
</html>"#,
        url = escape(&report.url),
        styles = STYLES,
        rps = whole(stats.rps),
        requests = group(report.requests),
        errors = group(report.errors),
        mean = dec1(stats.mean_ms),
        p99 = dec1(stats.p99),
        secs = dec1(report.elapsed_ms as f64 / 1000.0),
        chart = chart(&stats),
        p50 = dec1(stats.p50),
        p75 = dec1(stats.p75),
        p90 = dec1(stats.p90),
        p95 = dec1(stats.p95),
        max = dec1(stats.max_ms),
    );
    std::fs::write(path, page)?;
    Ok(())
}

fn chart(stats: &Stats) -> String {
    if stats.histogram.is_empty() {
        return String::new();
    }
    let width = 720.0;
    let height = 200.0;
    let pad = 16.0;
    let max_count = stats
        .histogram
        .iter()
        .map(|b| b.count)
        .max()
        .unwrap_or(1)
        .max(1) as f64;
    let n = stats.histogram.len() as f64;
    let slot = width / n;
    let bw = (slot - 4.0).max(2.0);

    let mut bars = String::new();
    for (i, b) in stats.histogram.iter().enumerate() {
        let h = (b.count as f64 / max_count) * (height - pad);
        let x = i as f64 * slot + 2.0;
        let (r, g, bl) = heat((b.hi / stats.max_ms.max(1.0)).clamp(0.0, 1.0));
        bars.push_str(&format!(
            r#"<rect x="{x:.1}" y="{y:.1}" width="{bw:.1}" height="{h:.1}" rx="2" fill="rgb({r},{g},{bl})"/>"#,
            x = x,
            y = height - h,
            bw = bw,
            h = h,
            r = r,
            g = g,
            bl = bl,
        ));
    }
    let x0 = format!(
        r##"<text x="2" y="{y:.0}" fill="#666" font-size="11">0</text>"##,
        y = height - 4.0
    );
    let x1 = format!(
        r##"<text x="{x:.0}" y="{y:.0}" fill="#666" font-size="11">{m:.1} ms</text>"##,
        x = width - 60.0,
        y = height - 4.0,
        m = stats.max_ms,
    );
    format!(
        r#"<svg viewBox="0 0 {w:.0} {h:.0}" xmlns="http://www.w3.org/2000/svg">{bars}{x0}{x1}</svg>"#,
        w = width,
        h = height,
    )
}

fn escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}
